package es.fplumara.dam1.alumnos.repository;

import es.fplumara.dam1.alumnos.model.Curso;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class CursoRepositoryDB implements CursoRepository {

    private final String url;
    private final String user;
    private final String pass;

    public CursoRepositoryDB(String url, String user, String pass) {
        this.url = url;
        this.user = user;
        this.pass = pass;
    }


    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(url, user, pass);
    }

    @Override
    public void initSchema() {
        String ddl = """
                CREATE TABLE IF NOT EXISTS cursos (
                  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    estado boolean default  0,
                  nombre VARCHAR(100) NOT NULL
                
                
                );
                """;


        try {
            Connection c = getConnection();
            Statement st = c.createStatement();
            st.execute(ddl);

        } catch (SQLException e) {
            throw new RuntimeException("Error del esquema");
        }
    }


    @Override
    public Optional<Curso> findById(Integer id) {
        if (id == null) {

            return Optional.empty();
        }
        //CONSULTA DE ENCONTRAR EN ID GUARDADA EN LA VARIABLE

        String sql = "SELECT id, nombre from cursos WHERE id = ?";

        try {
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();

            if (!rs.next()) {

                return Optional.empty();

            }
            return Optional.of(mapCursos(rs));
        } catch (SQLException e) {
            throw new RuntimeException("Error buscando alumno por id " + id, e);
        }

    }

    @Override
    public void activar(Integer id) { //pone activo a true

        if (id == null){

            throw new IllegalArgumentException("EL id no debe ser nulo");
        }

        String sql = "UPDATE cursos set estado = true where id = ? ";

        try {
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);
         ps.setInt(1,id);

         int rs = ps.executeUpdate();




         } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }

    @Override
    public void desactivar(Integer id) {

        if (id == null){

            throw new IllegalArgumentException("EL id no debe ser nulo");
        }

        String sql = "UPDATE cursos set estado = false where id = ? ";

        try {
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setInt(1,id);

            int rs = ps.executeUpdate();




        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }

    @Override
    public void eliminarSiNombreContiene(String texto) {

        if (texto == null){

            throw new IllegalArgumentException("tiene que contener texto");
        }

        String sql = "DELETE FROM cursos where nombre like ?";
        try{

            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);

            ps.setString(1, "%" + texto + "%");

            int rs = ps.executeUpdate();




        } catch (SQLException e) {
            throw new RuntimeException(e);
        }


    }

    @Override
    public List<Curso> listarPorEstado(Boolean estado) {

        String sql = "SELECT  * from cursos where estado = ?";
        List<Curso> cursos = new ArrayList<>();
        try{

            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);

            ps.setBoolean(1,estado);


            ResultSet rs = ps.executeQuery(); //resultset

            // creo la lista


            while (rs.next()) { //mientras haya otra fila entra
                Curso curso = new Curso(

                        rs.getInt("id"),

                        rs.getBoolean("estado"),
                        rs.getString("nombre")

                );
                cursos.add(curso);



            }


        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

        return cursos;
    }

    @Override
    public List<Curso> listarOrdenadorPor(String nombre, String tipoOrden) {

        String sql = "SELECT * from cursos order by nombre asc  ";




        return List.of();
    }


    @Override
    public Curso insert(Curso curso) {
        if (curso == null) throw new IllegalArgumentException("El curso no puede ser null");

        String sql = "INSERT INTO cursos ( estado, nombre) VALUES (?,?)";

        try (Connection c = getConnection(); PreparedStatement ps = c.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            ps.setBoolean(1, curso.isEstado());
            ps.setString(2, curso.getNombre());

            ps.executeUpdate();


            ResultSet keys = ps.getGeneratedKeys();

            if (keys.next()) {

                curso.setId(keys.getInt(1));
            }
            return curso;

        } catch (SQLException e) {
            throw new RuntimeException("Error al insertar el curso");
        }


    }

    @Override
    public Curso update(Curso curso) {
        if (curso == null) throw new IllegalArgumentException("El alumno no puede ser null");


        if (curso.getId() == null || curso.getId() <= 0) {
            throw new IllegalArgumentException("El id debe ser un entero");

        }

        String sql = "UPDATE cursos set estado=?, nombre=? where id=?";

        try {

            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);

            ps.setBoolean(1,curso.isEstado());
            ps.setString(2,curso.getNombre());

            int update = ps.executeUpdate();

            if (update == 0) {
                throw new IllegalArgumentException("No existe alumno con id " + curso.getId());
            }

            return  curso;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }

    @Override
    public List<Curso> findAll() {
        String sql = "SELECT * FROM cursos";
        try {
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            List<Curso> out = new ArrayList<>();
            while (rs.next()){
                out.add(mapCursos(rs));
            }
            return out;

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
    private Curso mapCursos(ResultSet rs) throws SQLException {
        return new Curso(
                rs.getInt("id"),
                rs.getBoolean("estado"),

                rs.getString("nombre")
        );
    }

}



