package es.fplumara.dam1.alumnos.repository;

import es.fplumara.dam1.alumnos.model.Alumno;
import es.fplumara.dam1.alumnos.model.Curso;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class CursoRepositoryDB implements CursoRepository {

    private final String url;
    private final String user;
    private final String pass;

    public CursoRepositoryDB(String url, String user, String pass) {
        this.url = url;
        this.user = user;
        this.pass = pass;
    }


    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(url, user, pass);
    }

    @Override
    public void initSchema() {
        String ddl = """
                CREATE TABLE IF NOT EXISTS cursos (
                  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    estado boolean default  0;
                  nombre VARCHAR(100) NOT NULL,
                
                
                );
                """;


        try {
            Connection c = getConnection();
            Statement st = c.createStatement();
            st.execute(ddl);

        } catch (SQLException e) {
            throw new RuntimeException("Error del esquema");
        }
    }


    @Override
    public Optional<Curso> findById(Integer id) {
        if (id == null) {

            return Optional.empty();
        }
        //CONSULTA DE ENCONTRAR EN ID GUARDADA EN LA VARIABLE

        String sql = "SELECT id, nombre from cursos WHERE id = ?";

        try {
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();

            if (!rs.next()) {

                return Optional.empty();

            }
            return Optional.of(mapCursos(rs));
        } catch (SQLException e) {
            throw new RuntimeException("Error buscando alumno por id " + id, e);
        }

    }


    @Override
    public Curso insert(Curso curso) {
        if (curso == null) throw new IllegalArgumentException("El curso no puede ser null");

        String sql = "INSERT INTO cursos ( estado, nombre) VALUES (?,?)";

        try (Connection c = getConnection(); PreparedStatement ps = c.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setBoolean(1, curso.isEstado());
            ps.setString(2, curso.getNombre());

            ps.executeUpdate();


            ResultSet keys = ps.getGeneratedKeys();

            if (keys.next()) {

                curso.setId(keys.getInt(1));
            }
            return curso;

        } catch (SQLException e) {
            throw new RuntimeException("Error al insertar el curso");
        }


    }

    @Override
    public Curso update(Curso curso) {
        return null;
    }

    @Override
    public List<Curso> findAll() {
        return List.of();
    }


    @Override
    public boolean activo(boolean estado) {
        return false;
    }

    @Override
    public void eliminarSiNombreContiene() {

    }

    @Override
    public List<Curso> listarPorEstado(Boolean estado) {
        return List.of();
    }


    private Curso mapCursos(ResultSet rs) throws SQLException {
        return new Curso(
                rs.getInt("id"),
                rs.getBoolean("estado"),

                rs.getString("nombre")
        );
    }


}
